import React, { useState } from 'react';
import './PendingToolsPanel.css';

const PendingToolsPanel = ({ pendingTools, onApprove, onReject, onViewCode, onRunTests }) => {
  const [processingToolId, setProcessingToolId] = useState(null);
  const [testingToolId, setTestingToolId] = useState(null);

  const getToolTypeColor = (type) => {
    return type === 'new_tool' ? '#10b981' : '#3b82f6';
  };

  const getToolTypeLabel = (type) => {
    return type === 'new_tool' ? 'NEW TOOL' : 'UPDATE';
  };

  const getRiskColor = (risk) => {
    const colors = {
      low: '#10b981',
      medium: '#f59e0b',
      high: '#ef4444',
      critical: '#dc2626'
    };
    return colors[risk?.toLowerCase()] || '#6b7280';
  };

  const handleApproveClick = async (toolId) => {
    if (processingToolId) return;
    setProcessingToolId(toolId);
    try {
      await onApprove(toolId);
    } finally {
      setProcessingToolId(null);
    }
  };

  const handleRejectClick = async (toolId) => {
    if (processingToolId) return;
    setProcessingToolId(toolId);
    try {
      await onReject(toolId);
    } finally {
      setProcessingToolId(null);
    }
  };

  const handleRunTests = async (toolId) => {
    if (testingToolId) return;
    setTestingToolId(toolId);
    try {
      await onRunTests(toolId);
    } finally {
      setTestingToolId(null);
    }
  };

  return (
    <div className="pending-tools-panel">
      <div className="panel-header">
        <h2>Pending Tools ({pendingTools.length})</h2>
        <p className="subtitle">Review and approve tools before activation</p>
      </div>

      {pendingTools.length === 0 ? (
        <div className="empty-state">
          <div className="empty-icon">[ ]</div>
          <p>No pending tools</p>
          <span className="empty-hint">Tools will appear here when generated by self-improvement</span>
        </div>
      ) : (
        <div className="tools-list">
          {pendingTools.map((tool) => (
            <div
              key={tool.tool_id}
              className="tool-card"
              style={{ borderLeft: `4px solid ${getToolTypeColor(tool.type)}` }}
            >
              <div className="tool-header">
                <div className="tool-title-row">
                  <span
                    className="tool-type-badge"
                    style={{ backgroundColor: getToolTypeColor(tool.type) }}
                  >
                    {getToolTypeLabel(tool.type)}
                  </span>
                  <h3 className="tool-name">
                    {tool.tool_file?.split('/').pop()?.replace('.py', '') || 'Unknown Tool'}
                  </h3>
                </div>
                <span
                  className="risk-badge"
                  style={{ backgroundColor: getRiskColor(tool.risk_score) }}
                >
                  {tool.risk_score?.toUpperCase() || 'UNKNOWN'} RISK
                </span>
              </div>

              <p className="tool-description">{tool.description}</p>

              <div className="tool-details">
                <div className="detail-item">
                  <span className="detail-label">File:</span>
                  <code className="detail-value">{tool.tool_file}</code>
                </div>

                {tool.test_file && (
                  <div className="detail-item">
                    <span className="detail-label">Tests:</span>
                    <code className="detail-value">{tool.test_file}</code>
                  </div>
                )}

                {tool.test_results && (
                  <div className="detail-item">
                    <span className="detail-label">Test Results:</span>
                    <span className={`test-status ${tool.test_results.success ? 'passed' : 'failed'}`}>
                      {tool.test_results.success ? 'PASS' : 'FAIL'}
                      {' '}
                      {tool.test_results.tests_passed || 0}/{tool.test_results.tests_total || 0} passed
                    </span>
                  </div>
                )}

                {!tool.test_results && tool.sandbox_note && (
                  <div className="sandbox-note" style={{background: 'rgba(59, 130, 246, 0.1)', padding: '10px', borderRadius: '6px', marginTop: '10px'}}>
                    <strong style={{color: '#3b82f6'}}>ℹ️ Sandbox Note:</strong>
                    <div style={{marginTop: '5px', color: 'var(--text-secondary)'}}>
                      {tool.sandbox_note}
                    </div>
                    <div style={{marginTop: '5px', fontSize: '0.9em', color: 'var(--text-tertiary)'}}>
                      Run LLM tests to validate functionality
                    </div>
                  </div>
                )}

                {tool.dependencies && (tool.dependencies.missing_libraries?.length > 0 || tool.dependencies.missing_services?.length > 0) && (
                  <div className="dependencies-warning" style={{background: 'rgba(239, 68, 68, 0.1)', padding: '10px', borderRadius: '6px', marginTop: '10px'}}>
                    <strong style={{color: '#ef4444'}}>⚠️ Missing Dependencies:</strong>
                    {tool.dependencies.missing_libraries?.length > 0 && (
                      <div style={{marginTop: '5px'}}>
                        <span style={{color: 'var(--text-secondary)'}}>Libraries:</span> {tool.dependencies.missing_libraries.join(', ')}
                      </div>
                    )}
                    {tool.dependencies.missing_services?.length > 0 && (
                      <div style={{marginTop: '5px'}}>
                        <span style={{color: 'var(--text-secondary)'}}>Services:</span> {tool.dependencies.missing_services.join(', ')}
                      </div>
                    )}
                  </div>
                )}

                <div className="detail-item">
                  <span className="detail-label">Created:</span>
                  <span className="detail-value">
                    {new Date(tool.created_at).toLocaleString()}
                  </span>
                </div>
              </div>

              <div className="tool-actions">
                <button
                  className="btn-view-code"
                  onClick={() => onViewCode(tool)}
                  disabled={processingToolId === tool.tool_id || testingToolId === tool.tool_id}
                >
                  View Code
                </button>
                <button
                  className="btn-test"
                  onClick={() => handleRunTests(tool.tool_id)}
                  disabled={processingToolId === tool.tool_id || testingToolId === tool.tool_id}
                  style={{backgroundColor: '#f59e0b'}}
                >
                  {testingToolId === tool.tool_id ? 'Testing...' : 'Run Tests'}
                </button>
                <button
                  className="btn-reject"
                  onClick={() => handleRejectClick(tool.tool_id)}
                  disabled={processingToolId === tool.tool_id || testingToolId === tool.tool_id}
                >
                  Reject
                </button>
                <button
                  className="btn-approve"
                  onClick={() => handleApproveClick(tool.tool_id)}
                  disabled={(tool.test_results && !tool.test_results.success) || processingToolId === tool.tool_id || testingToolId === tool.tool_id}
                >
                  {processingToolId === tool.tool_id ? 'Processing...' : 'Approve & Activate'}
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default PendingToolsPanel;
